// <auto-generated />
using FlyMaps.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlyMaps.Migrations
{
    [DbContext(typeof(BioDataDbContext))]
    [Migration("20260108124222_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FlyMaps.Models.DbLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("GeneId")
                        .HasColumnType("int");

                    b.Property<string>("SourceDb")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceDbId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GeneId");

                    b.ToTable("DbLink");
                });

            modelBuilder.Entity("FlyMaps.Models.Gene", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.PrimitiveCollection<string>("Aliases")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genes");
                });

            modelBuilder.Entity("FlyMaps.Models.GeneSummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("GeneId")
                        .HasColumnType("int");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GeneId");

                    b.ToTable("GeneSummary");
                });

            modelBuilder.Entity("FlyMaps.Models.DbLink", b =>
                {
                    b.HasOne("FlyMaps.Models.Gene", null)
                        .WithMany("DbLinks")
                        .HasForeignKey("GeneId");
                });

            modelBuilder.Entity("FlyMaps.Models.GeneSummary", b =>
                {
                    b.HasOne("FlyMaps.Models.Gene", null)
                        .WithMany("Summaries")
                        .HasForeignKey("GeneId");
                });

            modelBuilder.Entity("FlyMaps.Models.Gene", b =>
                {
                    b.Navigation("DbLinks");

                    b.Navigation("Summaries");
                });
#pragma warning restore 612, 618
        }
    }
}
